# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SeeFood-BlueMix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SeeFood-BlueMix
    pod 'IBMWatsonAssistantV1', '~> 3.5.0'
    pod 'IBMWatsonAssistantV2', '~> 3.5.0'
    pod 'IBMWatsonCompareComplyV1', '~> 3.5.0'
    pod 'IBMWatsonDiscoveryV1', '~> 3.5.0'
    pod 'IBMWatsonLanguageTranslatorV3', '~> 3.5.0'
    pod 'IBMWatsonNaturalLanguageClassifierV1', '~> 3.5.0'
    pod 'IBMWatsonNaturalLanguageUnderstandingV1', '~> 3.5.0'
    pod 'IBMWatsonPersonalityInsightsV3', '~> 3.5.0'
    pod 'IBMWatsonSpeechToTextV1', '~> 3.5.0'
    pod 'IBMWatsonTextToSpeechV1', '~> 3.5.0'
    pod 'IBMWatsonToneAnalyzerV3', '~> 3.5.0'
    pod 'IBMWatsonVisualRecognitionV3', '~> 3.5.0'

end
