# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flash Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flash Chat

	# add the Firebase pod for Google Analytics
  pod 'Firebase'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Analytics'
	pod 'SVProgressHUD'
	pod 'ChameleonFramework'
	# add pods for any other desired Firebase products
	# https://firebase.google.com/docs/ios/setup#available-pods

end
